// Code generated by "sqlc-gen-zz". DO NOT EDIT.

package c

import (
	"encoding/json"
	"time"

	"github.com/nzoschke/sqlc-gen-zz/pkg/sql/models"
)

type Contact struct {
	Blob      []byte      `json:"blob"`
	CreatedAt time.Time   `json:"created_at"`
	Id        int64       `json:"id"`
	Info      models.Info `json:"info"`
	Name      string      `json:"name"`
}

func catalogImports() {
	_ = json.Decoder{}
	_ = time.Time{}
}
