// Code generated by "sqlc-gen-zz". DO NOT EDIT.

package c

import (
	"encoding/json"

	"github.com/nzoschke/sqlc-gen-zz/pkg/sql/models"
)

func jsonMarshal(v any) []byte {
	bs, _ := json.Marshal(v)
	return bs
}

func unmarshalModelsBook(bs []byte) models.Book {
	var v models.Book
	json.Unmarshal(bs, &v)
	return v
}
